package com.claude.poem.ui.theme

import androidx.compose.ui.graphics.Color

// ===== LIGHT MODE =====
val ClaudePrimary = Color(0xFFD97757)
val ClaudeOnPrimary = Color(0xFFFFFFFF)
val ClaudePrimaryContainer = Color(0xFFFAE5D8)
val ClaudeOnPrimaryContainer = Color(0xFF5C2A11)
val ClaudeSecondary = Color(0xFF8B6F5C)
val ClaudeOnSecondary = Color(0xFFFFFFFF)
val ClaudeSecondaryContainer = Color(0xFFF0E1D2)
val ClaudeOnSecondaryContainer = Color(0xFF332011)
val ClaudeTertiary = Color(0xFF7A6B4E)
val ClaudeOnTertiary = Color(0xFFFFFFFF)
val ClaudeTertiaryContainer = Color(0xFFEFE3CB)
val ClaudeOnTertiaryContainer = Color(0xFF2A1F07)
val ClaudeBackground = Color(0xFFF5F0EB)
val ClaudeOnBackground = Color(0xFF1D1B18)
val ClaudeSurface = Color(0xFFFAF6F1)
val ClaudeOnSurface = Color(0xFF1D1B18)
val ClaudeSurfaceVariant = Color(0xFFECE3D6)
val ClaudeOnSurfaceVariant = Color(0xFF4C443C)
val ClaudeOutline = Color(0xFFA89986)
val ClaudeOutlineVariant = Color(0xFFD8CDBC)
val ClaudeError = Color(0xFFB3261E)
val ClaudeOnError = Color(0xFFFFFFFF)

// ===== DARK MODE =====
val ClaudePrimaryDark = Color(0xFFFFB59E)
val ClaudeOnPrimaryDark = Color(0xFF5C2A11)
val ClaudePrimaryContainerDark = Color(0xFF994B2F)
val ClaudeOnPrimaryContainerDark = Color(0xFFFAE5D8)
val ClaudeSecondaryDark = Color(0xFFD4BEA9)
val ClaudeOnSecondaryDark = Color(0xFF3B2B1B)
val ClaudeSecondaryContainerDark = Color(0xFF554335)
val ClaudeOnSecondaryContainerDark = Color(0xFFF0E1D2)
val ClaudeTertiaryDark = Color(0xFFD3C7AF)
val ClaudeOnTertiaryDark = Color(0xFF2A1F07)
val ClaudeTertiaryContainerDark = Color(0xFF4A412D)
val ClaudeOnTertiaryContainerDark = Color(0xFFEFE3CB)
val ClaudeBackgroundDark = Color(0xFF1A1816)
val ClaudeOnBackgroundDark = Color(0xFFE8E2D9)
val ClaudeSurfaceDark = Color(0xFF2A2520)
val ClaudeOnSurfaceDark = Color(0xFFE8E2D9)
val ClaudeSurfaceVariantDark = Color(0xFF4C443C)
val ClaudeOnSurfaceVariantDark = Color(0xFFCFC5B8)
val ClaudeOutlineDark = Color(0xFF998E81)
val ClaudeOutlineVariantDark = Color(0xFF4C443C)
val ClaudeErrorDark = Color(0xFFFFB4AB)
val ClaudeOnErrorDark = Color(0xFF690005)
